apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "webhook-relay.fullname" . }}
  labels:
    {{- include "webhook-relay.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.appConfig.port | quote }}
  WORKER_CONCURRENCY: {{ .Values.appConfig.workerConcurrency | quote }}
  MAX_RETRIES: {{ .Values.appConfig.maxRetries | quote }}
  RETRY_BASE_DELAY: {{ .Values.appConfig.retryBaseDelay | quote }}
  DELIVERY_TIMEOUT: {{ .Values.appConfig.deliveryTimeout | quote }}
  POLL_INTERVAL: {{ .Values.appConfig.pollInterval | quote }}
  POSTGRES_USER: {{ .Values.postgres.user | quote }}
  POSTGRES_DB: {{ .Values.postgres.database | quote }}
