apiVersion: v1
kind: Service
metadata:
  name: {{ include "webhook-relay.fullname" . }}-redis
  labels:
    {{- include "webhook-relay.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  clusterIP: None
  selector:
    {{- include "webhook-relay.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
  ports:
    - port: 6379
      targetPort: redis
      protocol: TCP
      name: redis
