{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "webhook-relay.fullname" . }}
  labels:
    {{- include "webhook-relay.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_URL: {{ include "webhook-relay.databaseUrl" . | b64enc | quote }}
  REDIS_URL: {{ include "webhook-relay.redisUrl" . | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | b64enc | quote }}
{{- end }}
